sudo: required

language: go

go:
  - 1.7

services:
  - docker

install:
  - nvm version
  - node -v
  - make install_ci

script:
  - make test_ci
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci || true

